type Mutation {
  approveStepRun(
    arg1: ApproveStepRunInput!
  ): ApproveStepRunOutput
}

type Mutation {
  triggerWorkflowRun(
    arg1: TriggerWorkflowRunInput!
  ): TriggerWorkflowRunOutput
}

input TriggerWorkflowRunInput {
  workflow_id: uuid!
  input: jsonb
}

input ApproveStepRunInput {
  step_run_id: uuid!
}

type TriggerWorkflowRunOutput {
  run_id: String
  status: String!
  message: String!
  output: jsonb
}

type ApproveStepRunOutput {
  step_run_id: String
  status: String!
  message: String!
}

scalar uuid

scalar jsonb

